version: "3.3"

services:
  library-db:
    restart: always
    image: sameersbn/postgresql:10-2
    environment:
      - PG_TRUST_LOCALNET=true
      - DB_NAME=library
      - DB_USER=postgres
      - DB_PASS=postgres
      - PG_RUNDIR=/run/postgres
      - PG_LOGDIR=/var/log/postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql

  library-app:
    image: library-app-image:0.0.1-SNAPSHOT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-db:5432/library
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    depends_on:
      - library-db

volumes:
  data:
  logs: